name: Global Traffic Graph
on:
  schedule:
    - cron: "0 * * * *" # Toutes les heures
  workflow_dispatch: # Pour le lancer à la main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Traffic
        uses: sangonzal/repository-traffic-action@v0.3.4
        with:
          TOKEN: ${{ secrets.TRAFFIC_TOKEN }}
          REPOSITORY: LTX128/Best-setting_user-for-key-fob
